name: Release

on:
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ITCH_USERNAME: structed
  ITCH_GAME_ID: godot-playfab

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-playfab-${{ env.version }}
          path: addons/godot-playfab/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ env.version }}
          draft: true
          prerelease: true
          artifacts: addons/godot-playfab/
          generateReleaseNotes: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}

  itch:
    runs-on: ubuntu-latest
    needs: release

    steps:

      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # Using https://github.com/KikimoraGames/itch-publish
      - uses: actions/download-artifact@v3
        with:
          name: godot-playfab-${{ env.version }}
          path: addons/godot-playfab/

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.GODOT_PLAYFAB_ITCHIO_SECRET}}
          gameData: .
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: windows-mac-linux
          buildNumber: ${{ env.version }}
