name: Release

on:
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ITCH_USERNAME: structed
  ITCH_GAME_ID: godot-playfab
  ASSET_LIB_USERNAME: structed
  ASSET_LIB_PASSSWORD: ${{ secrets.ASSET_STORE_PASSWORD }}
  ASSET_LIB_ASSET_ID: 1321

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-playfab-${{ env.version }}
          path: addons/godot-playfab/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ env.version }}
          draft: true
          prerelease: true
          artifacts: ""
          replacesArtifacts: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}

  itch:
    runs-on: ubuntu-latest
    needs: release

    steps:

      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      # Using https://github.com/KikimoraGames/itch-publish
      - uses: actions/download-artifact@v3
        with:
          name: godot-playfab-${{ env.version }}
          path: addons/godot-playfab/

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.GODOT_PLAYFAB_ITCHIO_SECRET}}
          gameData: .
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: windows-mac-linux
          buildNumber: ${{ env.version }}

  assetlib:
    runs-on: ubuntu-latest
    needs: release
    name: Publish new version to asset lib
    steps:

      - name: Set Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV


      - uses: actions/checkout@v3

      - name: Godot Asset Lib
        uses: deep-entertainment/godot-asset-lib-action@v0.4.0
        with:
          username: ${{ env.ASSET_LIB_USERNAME }}
          password: ${{ env.ASSET_LIB_PASSSWORD }}
          assetId: ${{ env.ASSET_LIB_ASSET_ID }}
